## -----------------------------------------------
## Basic Configuration
## -----------------------------------------------

title = "Sarama"
theme = "hugo-story"


## -----------------------------------------------
## Hugo Built-in Features
## -----------------------------------------------

disableKinds = ["taxonomy", "taxonomyTerm", "section"]
# googleAnalytics = "your-google-analytics-id"


## -----------------------------------------------
## Site Parameters
## -----------------------------------------------

[Params]
  description = "Developing a spoken language between dogs and people."
  logo = "images/banner.jpg"
  favicon = true

[Params.social]
  github = "https://github.com/saramaxyz/"
  email = "hello@sarama.xyz"
  linkedin = "https://www.linkedin.com/company/sarama"
