name: Build and Deploy
on: 
  push:
    branches:
      - figma_design
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false

      - name: Cache
        uses: actions/cache@v2
        with:
          path: ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/yarn.lock') }}

      - name: Install, Build, Deploy
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: yarn
      - run: yarn deploy
